### ISSUE TITLE
link naar niet-bestaande webservice

### ISSUE THREAD

**Issue by Irishx** [proycon/valkuil-gecco#3]
In README:

Hoe kan ik Valkuil zelf draaien? De makkelijkste optie is door vanuit je programma verbinding te maken met onze Valkuil webservice, zie https://webservices-lst.science.ru.nl .

Maar Valkuil staat nu niet bij de services.

Suggestgie: Evt een instructie toevoegen hoe je de webservice aanroept in je code?

**Comment by proycon** [comment]
Er is iets mis inderdaad, de webservice is er gewoon (https://webservice-lst.science.ru.nl/valkuil) maar toont blijkbaar niet in de portal..

En met valkuil.net is ook iets mis momenteel kom ik nu achter...
